# -*- coding: utf-8 -*-
"""IDPDesigner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDJ1XI-O9EnFKyybR0og7FcofIatkIQY

<a href="https://colab.research.google.com/github/Sabian98/idp-rl/blob/main/IDPDesigner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**General information**

This Colab notebook enables to design sequence of IDPs with target scaling exponents ($\nu$) and radius of gyration ($r_g$).

The user needs to provide as input a starting sequence and a target value for $\nu$. The starting sequence can be evolved with swap moves or single point mutations.
"""

#@title <b>Preliminary operations (i)</b>
import random
random.seed(42)
import subprocess
import os
import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np
import itertools
from joblib import dump, load
!pip install wget
!pip install localcider
!pip install scikit-learn

!pip install idptools-parrot --quiet;
!pip install git+https://git@github.com/idptools/sparrow.git --quiet;
import wget
from localcider.sequenceParameters import SequenceParameters
import matplotlib.pyplot as plt
from google.colab import files
from ipywidgets import IntProgress
from IPython.display import display
from IPython.display import clear_output
import warnings
warnings.filterwarnings('ignore')
import sklearn

# ! pip install fair-esm

# Commented out IPython magic to ensure Python compatibility.


# Install from GitHub
!git clone https://github.com/doszilab/AIUPred
# %cd AIUPred
!pip install torch>=2.2.0 torchvision
!pip install -r requirements.txt --no-deps || pip install numpy scipy matplotlib seaborn pandas
import sys
sys.path.append('.')
import aiupred_lib

# # Test some well-characterized IDPs
# known_idps = [
#     "MKTAYAIILQGQTQSSDILYQYLRNSAAKQASGVNQEPKPNKGTKVLDNVMAKATGKVRQGLEDLPPKSVSAENVQPGCV",  # p53 TAD
#     "MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDT",  # Calmodulin
#     # Add more known IDPs
# ]

# for idp_seq in known_idps:
#     _, mean_score = get_esm2_likelihood(idp_seq)
#     print(f"IDP: {mean_score}")

import random
import pandas as pd
import numpy as np
import sparrow
from sparrow.predictors.batch_predict import batch_predict
import aiupred_lib
import math

# Amino acid classifications
positive = ['K', 'R', 'H']
negative = ['D', 'E']
neutral = ['A', 'C', 'F', 'G', 'I', 'L', 'M', 'N', 'P', 'Q', 'S', 'T', 'V', 'W', 'Y']
charged = positive + negative

class Sequence:
    aa = ['A','C','D','E','F','G','H','I','K','L','M','N','P','Q','R','S','T','V','W','Y']

    def __init__(self, start_seq, masked_seq, boundaries, mask_char='X', length=None, pH=7.):
        assert start_seq is not None or length is not None, "Either initialize a starting sequence or specify a sequence length so that a random sequence is initialized!"
        self.pH = pH
        self.boundaries = boundaries
        self.masked_seq = masked_seq
        self.start_seq = start_seq
        if start_seq is None and length is not None:
            self.sequence = random.choices(self.aa, k=length)
        else:
            self.sequence = list(masked_seq)

        self.mask_char = mask_char

        masked_count = self.sequence.count(mask_char)
        self.length = len(self.sequence) - masked_count

    def get_sequence(self):
        return ''.join(self.sequence)


# Utility functions
def count_charged_residues(sequence):
    """Count the number of charged residues in a sequence"""
    if isinstance(sequence, list):
        seq_str = ''.join(sequence)
    else:
        seq_str = sequence

    charged_count = 0
    for aa in seq_str:
        if aa in charged:
            charged_count += 1
    return charged_count


def calculate_charge_penalty(current_charge_fraction, target_charge_fraction, tolerance=0.02):
    """
    Calculate penalty based on deviation from target charge fraction

    Args:
        current_charge_fraction: Current fraction of charged residues (0-1)
        target_charge_fraction: Target fraction of charged residues (0-1)
        tolerance: Allowed deviation without penalty

    Returns:
        penalty: Value between 0 (no penalty) and 1 (maximum penalty)
    """
    deviation = abs(current_charge_fraction - target_charge_fraction)

    if deviation <= tolerance:
        return 0.0  # No penalty within tolerance

    # Linear penalty beyond tolerance
    penalty = min(1.0, (deviation - tolerance) * 10)
    return penalty


def calculate_target_charge_fraction(sequence):
    """Calculate target charge fraction from original sequence"""
    return count_charged_residues(sequence) / len(sequence)


def get_charge_distribution(sequence):
    """Get detailed charge distribution statistics"""
    if isinstance(sequence, list):
        seq_str = ''.join(sequence)
    else:
        seq_str = sequence

    pos_count = sum(1 for aa in seq_str if aa in positive)
    neg_count = sum(1 for aa in seq_str if aa in negative)
    neutral_count = sum(1 for aa in seq_str if aa in neutral)

    total = len(seq_str)

    return {
        'positive_count': pos_count,
        'negative_count': neg_count,
        'neutral_count': neutral_count,
        'positive_fraction': pos_count / total,
        'negative_fraction': neg_count / total,
        'neutral_fraction': neutral_count / total,
        'total_charged_fraction': (pos_count + neg_count) / total,
        'charge_balance': pos_count - neg_count
    }


# Helper function to check if position is mutable
def is_mutable_position(position, masked_seq, mask_char='X'):
    """Check if a position can be mutated (not protected)"""
    return position < len(masked_seq) and masked_seq[position] != mask_char


# Mutation functions with protection
def same_charge_mutation(sequence, masked_seq, mask_char='X'):
    """Mutate to amino acid of same charge type - only mutable positions"""
    charged_positions = [i for i, aa in enumerate(sequence)
                        if aa in charged and is_mutable_position(i, masked_seq, mask_char)]
    if not charged_positions:
        return sequence

    pos = random.choice(charged_positions)
    current_aa = sequence[pos]

    if current_aa in positive:
        candidates = [aa for aa in positive if aa != current_aa]
    else:  # negative
        candidates = [aa for aa in negative if aa != current_aa]

    if not candidates:  # Safety check
        return sequence

    new_sequence = sequence.copy()
    new_sequence[pos] = random.choice(candidates)
    return new_sequence


def charged_to_neutral_mutation(sequence, masked_seq, mask_char='X'):
    """Convert charged residue to neutral - only mutable positions"""
    charged_positions = [i for i, aa in enumerate(sequence)
                        if aa in charged and is_mutable_position(i, masked_seq, mask_char)]
    if not charged_positions:
        return sequence

    pos = random.choice(charged_positions)
    new_sequence = sequence.copy()
    new_sequence[pos] = random.choice(neutral)
    return new_sequence


def segregation_breaking_mutation(sequence, masked_seq, mask_char='X'):
    """Break up charge blocks by inserting opposite charges - only mutable positions"""
    blocks = find_charge_blocks(sequence)
    if len(blocks) < 2:
        return sequence

    # Filter blocks to only include mutable positions
    mutable_blocks = []
    for block in blocks:
        mutable_positions = [pos for pos in block['positions']
                           if is_mutable_position(pos, masked_seq, mask_char)]
        if len(mutable_positions) >= 3:  # Need at least 3 mutable residues
            mutable_blocks.append({
                'charge_type': block['charge_type'],
                'positions': mutable_positions
            })

    if not mutable_blocks:
        return sequence

    block = random.choice(mutable_blocks)
    middle_pos = block['positions'][len(block['positions'])//2]
    new_sequence = sequence.copy()

    if block['charge_type'] == 'positive':
        new_sequence[middle_pos] = random.choice(negative)
    else:
        new_sequence[middle_pos] = random.choice(positive)

    return new_sequence


def segregation_enhancing_mutation(sequence, masked_seq, mask_char='X'):
    """Enhance segregation by moving like charges together - only mutable positions"""
    charged_positions = [i for i, aa in enumerate(sequence)
                        if aa in charged and is_mutable_position(i, masked_seq, mask_char)]
    if len(charged_positions) < 2:
        return sequence

    # Find a charged residue that's isolated
    isolated_positions = []
    for pos in charged_positions:
        current_charge = sequence[pos]
        neighbors_same_charge = False

        # Check neighbors
        for neighbor_pos in [pos-1, pos+1]:
            if (0 <= neighbor_pos < len(sequence) and
                get_charge_type(sequence[neighbor_pos]) == get_charge_type(current_charge)):
                neighbors_same_charge = True
                break

        if not neighbors_same_charge:
            isolated_positions.append(pos)

    if not isolated_positions:
        return sequence

    # Move isolated charge next to similar charge
    isolated_pos = random.choice(isolated_positions)
    isolated_charge = sequence[isolated_pos]
    charge_type = get_charge_type(isolated_charge)

    # Find mutable positions next to similar charges
    target_positions = []
    for pos in charged_positions:
        if get_charge_type(sequence[pos]) == charge_type and pos != isolated_pos:
            # Check adjacent positions
            for adj in [pos-1, pos+1]:
                if (0 <= adj < len(sequence) and
                    adj not in charged_positions and
                    is_mutable_position(adj, masked_seq, mask_char)):
                    target_positions.append(adj)

    if target_positions:
        target_pos = random.choice(target_positions)
        new_sequence = sequence.copy()

        # Swap isolated charge with neutral at target position
        new_sequence[isolated_pos] = sequence[target_pos]
        new_sequence[target_pos] = isolated_charge

        return new_sequence

    return sequence


def neutral_moves_mutation(sequence, masked_seq, mask_char='X'):
    """Mutate neutral residues - only mutable positions"""
    neutral_positions = [i for i, aa in enumerate(sequence)
                        if aa in neutral and is_mutable_position(i, masked_seq, mask_char)]
    if not neutral_positions:
        return sequence

    pos = random.choice(neutral_positions)
    current_aa = sequence[pos]
    candidates = [aa for aa in neutral if aa != current_aa]

    new_sequence = sequence.copy()
    new_sequence[pos] = random.choice(candidates)
    return new_sequence


def find_charge_blocks(sequence):
    """Find consecutive blocks of same charge type"""
    blocks = []
    current_block = None

    for i, aa in enumerate(sequence):
        charge_type = get_charge_type(aa)

        if charge_type in ['positive', 'negative']:
            if current_block and current_block['charge_type'] == charge_type:
                current_block['positions'].append(i)
            else:
                if current_block:
                    blocks.append(current_block)
                current_block = {'charge_type': charge_type, 'positions': [i]}
        else:
            if current_block:
                blocks.append(current_block)
                current_block = None

    if current_block:
        blocks.append(current_block)

    return blocks


def get_charge_type(aa):
    """Get charge type of amino acid"""
    if aa in positive:
        return 'positive'
    elif aa in negative:
        return 'negative'
    else:
        return 'neutral'


class SimulatedAnnealing(Sequence):
    def __init__(self, start_seq, masked_seq, boundaries,
                 mutation_mode, target_compaction, original_disorder,
                 disorder_weight=0.5, compaction_weight=0.5, target_charge_fraction=None,
                 max_edit_percentage=0.15,
                 c=0.003, gamma=0.01, tolerance=0.01, pH=7.):
        """
        Initialize SimulatedAnnealing optimizer

        Args:
            start_seq: Starting amino acid sequence
            masked_seq: Masked sequence with protected positions
            boundaries: Sequence boundaries
            mutation_mode: Type of mutations to use
            target_compaction: Dictionary with target compaction values
            original_disorder: Original disorder prediction to preserve
            disorder_weight: Weight for disorder preservation (0-1)
            compaction_weight: Weight for compaction optimization (0-1)
            target_charge_fraction: Target fraction of charged residues
            max_edit_percentage: Maximum allowed edit percentage (0-1, e.g., 0.1 = 10%)
            c: Initial temperature parameter
            gamma: Temperature decay parameter
            tolerance: Convergence tolerance
            pH: pH value for calculations
        """
        # Initialize parent class
        super().__init__(start_seq, masked_seq, boundaries, pH=pH)

        # Initialize AI models for disorder prediction
        self.embedding_model, self.regression_model, self.device = aiupred_lib.init_models('disorder')

        # Set optimization weights
        self.disorder_weight = disorder_weight
        self.compaction_weight = compaction_weight
        self.gamma = gamma
        self.target_compaction = target_compaction

        # Initialize charge fraction target
        if target_charge_fraction is None:
            self.target_charge_fraction = calculate_target_charge_fraction(start_seq)
        else:
            self.target_charge_fraction = target_charge_fraction

        # Edit control
        self.max_edit_percentage = max_edit_percentage
        mutable_positions = sum(1 for char in masked_seq if char != self.mask_char)
        self.max_edits = int(mutable_positions * max_edit_percentage)

        print(f"Mutable positions: {mutable_positions}")
        print(f"Max edit percentage: {max_edit_percentage*100:.1f}%")
        print(f"Max allowed edits: {self.max_edits}")

        # Current state - start with the original sequence
        self.sequence = list(start_seq)
        self.current_fitness = self.fitness_function(start_seq, original_disorder, target_compaction)
        self.best_sequence = self.sequence.copy()
        self.best_fitness = self.current_fitness
        self.current_nu = self.get_nu(self.get_sequence())

        # Algorithm parameters
        self.mode = mutation_mode
        self.original_disorder = original_disorder
        self.tolerance = tolerance
        self.c = c
        self.initial_c = c
        self.step_count = 0

        # Tracking variables
        self.history = []
        self.accepted_moves = 0
        self.converged = False

    def fitness_function(self, sequence, original_disorder, target_compaction):
        """
        Calculate fitness function combining compaction and disorder preservation.
        Returns a value between 0 and 1, where 1 is optimal.
        """
        try:
            # Compaction fitness
            current_compaction = self.get_nu(sequence)
            fitness_arr = []

            for key, value in current_compaction.items():
                if key in target_compaction:
                    target_value = target_compaction[key]
                    if target_value != 0:
                        compaction_deviation = abs(value - target_value) / abs(target_value)
                        fitness_arr.append(max(0.0, 1.0 - compaction_deviation))
                    else:
                        fitness_arr.append(1.0 if value == 0 else 0.0)

            compaction_fitness = np.mean(fitness_arr) if fitness_arr else 0.0

            # Disorder fitness - preserve original disorder profile
            current_disorder = aiupred_lib.predict_disorder(sequence, self.embedding_model,
                                                          self.regression_model, self.device)

            # Calculate MSE between disorder predictions
            mse = np.mean((np.array(original_disorder) - np.array(current_disorder))**2)
            disorder_fitness = np.exp(-mse * 10)  # Exponential decay

            # Charge fraction penalty
            current_charge_fraction = count_charged_residues(sequence) / len(sequence)
            charge_penalty = calculate_charge_penalty(current_charge_fraction, self.target_charge_fraction, tolerance=0.02)

            # Combine fitnesses (no edit distance penalty)
            total_fitness = (self.compaction_weight * compaction_fitness +
                           self.disorder_weight * disorder_fitness -
                           0.1 * charge_penalty)

            return max(0.0, min(1.0, total_fitness))

        except Exception as e:
            print(f"Error calculating fitness: {e}")
            return 0.0

    def get_nu(self, sequence):
        """Calculate compaction properties for a sequence"""
        current_compaction = {}

        if 'scaling_rg' in self.target_compaction:
            val_predictions = batch_predict([sequence], return_seq2prediction=True, network="scaled_rg")
            current_compaction['scaling_rg'] = list(val_predictions.values())[0]

        if 'scaling_exp' in self.target_compaction:
            val_predictions = batch_predict([sequence], return_seq2prediction=True, network="scaling_exponent")
            current_compaction['scaling_exp'] = list(val_predictions.values())[0]

        if 'asphericity' in self.target_compaction:
            val_predictions = batch_predict([sequence], return_seq2prediction=True, network="asphericity")
            current_compaction['asphericity'] = list(val_predictions.values())[0]

        if not current_compaction:
            raise ValueError("At least one compaction metric (scaling_rg, scaling_exp, or asphericity) must be in target_compaction")

        return current_compaction

    def get_sequence(self):
        return ''.join(self.sequence)


    def calculate_edit_distance(self, seq1, seq2):
        """
        Calculate Hamming distance (number of differing positions) between two sequences.
        Only counts mutable positions (non-masked regions).
        """
        if len(seq1) != len(seq2):
            return float('inf')

        edit_count = 0
        for i, (c1, c2) in enumerate(zip(seq1, seq2)):
            # Only count differences in mutable positions
            if is_mutable_position(i, self.masked_seq, self.mask_char) and c1 != c2:
                edit_count += 1

        return edit_count

    def distance_from_target(self):
        """Calculate normalized distance from target compaction"""
        try:
            current_nu = self.get_nu(self.get_sequence())
            distances = []

            for key, current_value in current_nu.items():
                if key in self.target_compaction:
                    target_value = self.target_compaction[key]
                    if target_value != 0:
                        distance = abs(current_value - target_value) / abs(target_value)
                    else:
                        distance = abs(current_value)
                    distances.append(distance)

            return np.mean(distances) if distances else float('inf')
        except Exception as e:
            print(f"Error calculating distance from target: {e}")
            return float('inf')

    def mutate(self, sequence):
        """Apply mutation to sequence based on weighted probabilities"""
        mutation_weights = {
            'same_charge': 0.4,
            'charged_to_neutral': 0.2,
            'segregation_breaking': 0.15,
            'segregation_enhancing': 0.15,
            'neutral_moves': 0.1
        }

        mutation_type = random.choices(
            list(mutation_weights.keys()),
            weights=list(mutation_weights.values())
        )[0]

        try:
            if mutation_type == 'same_charge':
                return same_charge_mutation(sequence, self.masked_seq, self.mask_char)
            elif mutation_type == 'charged_to_neutral':
                return charged_to_neutral_mutation(sequence, self.masked_seq, self.mask_char)
            elif mutation_type == 'segregation_breaking':
                return segregation_breaking_mutation(sequence, self.masked_seq, self.mask_char)
            elif mutation_type == 'segregation_enhancing':
                return segregation_enhancing_mutation(sequence, self.masked_seq, self.mask_char)
            else:  # neutral_moves
                return neutral_moves_mutation(sequence, self.masked_seq, self.mask_char)
        except Exception as e:
            print(f"Error in mutation {mutation_type}: {e}")
            return sequence  # Return original sequence if mutation fails

    def step(self):
        """Perform one step of simulated annealing"""
        # Check if already converged
        if self.converged:
            return False

        # Store current state
        old_sequence = self.sequence.copy()
        old_fitness = self.current_fitness

        # Propose new state
        new_sequence = self.mutate(self.sequence)

        # Skip if mutation didn't change anything
        if new_sequence == self.sequence:
            self.step_count += 1
            return not self.converged

        # HARD CONSTRAINT: Check edit distance
        edit_distance = self.calculate_edit_distance(new_sequence, self.start_seq)
        if edit_distance > self.max_edits:
            # Reject immediately if exceeds edit limit
            self.step_count += 1
            return not self.converged

        new_fitness = self.fitness_function(''.join(new_sequence), self.original_disorder, self.target_compaction)

        # Calculate energy difference (fitness difference, inverted for minimization)
        delta_E = old_fitness - new_fitness

        # Accept or reject
        accept = False
        if delta_E <= 0:  # Better solution (higher fitness)
            accept = True
        else:  # Worse solution - accept with probability
            if self.c > 0:
                probability = np.exp(-delta_E / self.c)
                accept = probability > random.random()

        if accept:
            # Keep the new state
            self.sequence = new_sequence
            self.current_fitness = new_fitness
            self.accepted_moves += 1

            # Track best solution found
            if new_fitness > self.best_fitness:
                self.best_sequence = self.sequence.copy()
                self.best_fitness = new_fitness

        # Check for convergence
        target_distance = self.distance_from_target()
        if target_distance <= self.tolerance:
            self.converged = True

        # Update step count and temperature
        self.step_count += 1
        if self.step_count % (self.length * 2) == 0:
            self.c = max(self.c * 0.99, self.initial_c * 0.001)

        # Record history
        if self.step_count % 100 == 0:
            self.history.append({
                'step': self.step_count,
                'fitness': self.current_fitness,
                'best_fitness': self.best_fitness,
                'target_distance': target_distance,
                'current_nu': self.get_nu(self.get_sequence()),
                'accepted': accept,
                'temperature': self.c,
                'acceptance_rate': self.get_acceptance_rate(),
                'edit_distance': self.calculate_edit_distance(self.sequence, self.start_seq)
            })

        return not self.converged

    def run(self, max_steps=None):
        """Run the simulated annealing until convergence or max_steps"""
        if max_steps is None:
            max_steps = self.length * 1000  # Default based on sequence length

        print(f"Starting simulated annealing optimization...")
        print(f"Initial fitness: {self.current_fitness:.6f}")
        print(f"Target distance: {self.distance_from_target():.6f}")

        step = 0
        while step < max_steps:
            if not self.step():  # Returns False when converged
                print(f"Converged after {self.step_count} steps!")
                break

            step += 1

            # Progress update
            if self.step_count % (max_steps // 10) == 0:
                print(f"Step {self.step_count}/{max_steps} - "
                      f"Best fitness: {self.best_fitness:.6f} - "
                      f"Distance: {self.distance_from_target():.6f} - "
                      f"Acceptance rate: {self.get_acceptance_rate():.3f}")

        # Final results
        print(f"\nOptimization completed!")
        print(f"Final step count: {self.step_count}")
        print(f"Final distance from target: {self.distance_from_target():.6f}")
        print(f"Best sequence: {self.get_best_solution()[0]}")
        print(f"Best fitness: {self.best_fitness:.6f}")
        print(f"Final acceptance rate: {self.get_acceptance_rate():.3f}")

    def run_until_target(self, max_steps=100000):
        """Run specifically until target is reached or max_steps"""
        return self.run(max_steps)

    def is_converged(self):
        """Check if the algorithm has converged"""
        return self.converged

    def fitness_score(self):
        """Return current best fitness score"""
        return self.best_fitness

    def get_best_solution(self):
        """Return the best solution found so far"""
        return ''.join(self.best_sequence), self.best_fitness

    def get_current_solution(self):
        """Return the current solution"""
        return ''.join(self.sequence), self.current_fitness

    def get_acceptance_rate(self):
        """Return the acceptance rate"""
        if self.step_count == 0:
            return 0
        return self.accepted_moves / self.step_count

    def get_history_df(self):
        """Return history as DataFrame"""
        return pd.DataFrame(self.history)

    def verify_motif_preservation(self):
        """Verify that protected motifs are unchanged"""
        current_seq = self.get_sequence()
        violations = []

        for i, (orig_char, mask_char) in enumerate(zip(self.start_seq, self.masked_seq)):
            if mask_char == self.mask_char:  # This position should be protected
                if i < len(current_seq) and current_seq[i] != orig_char:
                    violations.append((i, orig_char, current_seq[i]))

        if violations:
            print(f"WARNING: {len(violations)} protected positions changed:")
            for pos, orig, new in violations:
                print(f"  Position {pos}: {orig} -> {new}")
            return False
        return True

    def get_optimization_summary(self):
        """Get a summary of the optimization results"""
        best_seq, best_fit = self.get_best_solution()
        current_compaction = self.get_nu(best_seq)
        charge_dist = get_charge_distribution(best_seq)
        edit_distance = self.calculate_edit_distance(best_seq, self.start_seq)

        summary = {
            'converged': self.converged,
            'steps': self.step_count,
            'best_fitness': best_fit,
            'target_distance': self.distance_from_target(),
            'acceptance_rate': self.get_acceptance_rate(),
            'best_sequence': best_seq,
            'current_compaction': current_compaction,
            'target_compaction': self.target_compaction,
            'charge_distribution': charge_dist,
            'edit_distance': edit_distance,
            'max_edits': self.max_edits,
            'edit_percentage': (edit_distance / self.max_edits * 100) if self.max_edits > 0 else 0,
            'motif_preservation': self.verify_motif_preservation()
        }

        return summary

def mask_sequence_with_boundaries(sequence, boundaries, buffer_size=3, mask_char='X'):
    """
    Mask a protein sequence based on motif boundaries with optional buffer zones.

    Parameters:
    -----------
    sequence : str
        The protein sequence to mask
    boundaries : dict
        Dictionary with motif names as keys and (start, end) tuples as values
        Positions should be 0-indexed, end is exclusive (Python slicing convention)
    buffer_size : int, default=3
        Number of residues to add as buffer on each side of motif
    mask_char : str, default='X'
        Character to use for masking protected regions

    Returns:
    --------
    tuple: (masked_sequence, protected_positions)
        masked_sequence: sequence with protected regions replaced by mask_char
        protected_positions: set of all protected position indices
    """

    # Create set to track all protected positions
    protected_positions = set()

    # Process each motif boundary
    for motif_name, (start, end) in boundaries.items():
        # Add buffer zones
        buffered_start = max(0, start - buffer_size)
        buffered_end = min(len(sequence), end + buffer_size)

        # Add all positions in buffered region to protected set
        for pos in range(buffered_start, buffered_end):
            protected_positions.add(pos)

        print(f"Motif '{motif_name}': positions {start}-{end-1} "
              f"-> protected {buffered_start}-{buffered_end-1}")

    # Create masked sequence
    masked_sequence = ""
    for i, aa in enumerate(sequence):
        if i in protected_positions:
            masked_sequence += mask_char
        else:
            masked_sequence += aa

    # Print summary
    total_positions = len(sequence)
    protected_count = len(protected_positions)
    mutable_count = total_positions - protected_count


    return masked_sequence, protected_positions

compaction_dict={}

mutation_mode = 'single_point'

start_seq = "VLTKTKYTHYYGKKKNKRIGRPPGGHSNLACALKKASKRRKRRKNVFVHKKKRSSASVDNTPAGSPQGSGGEDEDDPDEGDDDSLSEGSTSEQQDELQEESEMSEKKSCSSSPTQSEISTSLPPDRQRRKRELRTFSFSDDENKPPSPKEIRIEVAERLHLD"#@param {type:"string"}
pH = 7.0
# tolerance = .01#@param {type:"number"}

scaling_exponent = True#@param {type:"boolean"}
target_scaling_exp=0.3#@param {type:"number"}
if scaling_exponent:
    compaction_dict['scaling_exp'] = target_scaling_exp

scaling_rg = False#@param {type:"boolean"}
target_rg=20#@param {type:"number"}
if scaling_rg:
    compaction_dict['scaling_rg'] = target_rg

asphericity= True #@param {type:"boolean"}
target_asphericity=0.3#@param {type:"number"}
if asphericity:
    compaction_dict['asphericity'] = target_asphericity

buffer_size = 2#@param {type:"number"}

esm2_likelihood_penalty= 0.01#@param {type:"number"}
boundaries = {
        "MOD_GSK3_1_1":(54,61),
        "MOD_GSK3_1":(83,90),
        "MOD_GSK3_1_2":(132,139)
}


print(f"Input sequence length: {len(start_seq)}")
# print(get_esm2_likelihood(start_seq))
masked_seq, _ = mask_sequence_with_boundaries(start_seq, boundaries, buffer_size=buffer_size)

embedding_model, regression_model, device = aiupred_lib.init_models('disorder')


original_disorder= aiupred_lib.predict_disorder(start_seq, embedding_model, regression_model, device)


sa = SimulatedAnnealing(
    start_seq=start_seq,
    masked_seq=masked_seq,
    boundaries=boundaries,
    target_compaction=compaction_dict,
    mutation_mode=mutation_mode,
    original_disorder=original_disorder,
    compaction_weight=0.5,
    disorder_weight=0.5,
    max_edit_percentage=0.15,  # Hard limit: 15% of mutable positions
    c=0.003,
    gamma=esm2_likelihood_penalty,
    pH=pH
)

print('\n')
print(f"target compaction:{compaction_dict}")
print(f"Starting sequence: {sa.get_sequence()}")
print(f"Starting compaction: {sa.current_nu}")

sa.run_until_target()

# Get comprehensive summary
summary = sa.get_optimization_summary()
print(f"\n=== Optimization Summary ===")
print(f"Converged: {summary['converged']}")
print(f"Edit distance: {summary['edit_distance']}/{summary['max_edits']} ({summary['edit_percentage']:.1f}%)")
print(f"Motif preservation: {'PASS' if summary['motif_preservation'] else 'FAIL'}")

df = sa.get_history_df()
print(df.iloc[-1])


# ================== FASTAPI ADAPTER (place at bottom of module) ==================

# Keep responses JSON-safe
def _to_py(x):
    import numpy as np
    if isinstance(x, (np.generic,)):
        return x.item()
    return x

def _to_py_recursive(obj):
    """Convert nested numpy/tensor types into plain Python."""
    import numpy as np
    if isinstance(obj, dict):
        return {k: _to_py_recursive(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [ _to_py_recursive(v) for v in obj ]
    if isinstance(obj, np.generic):
        return obj.item()
    return obj

# Optional: cache disorder models to avoid reloading per request
_EMB = _REG = _DEV = None
def _get_models():
    global _EMB, _REG, _DEV
    if _EMB is None or _REG is None or _DEV is None:
        _EMB, _REG, _DEV = aiupred_lib.init_models('disorder')
    return _EMB, _REG, _DEV

# Defaults you had in the notebook
_DEFAULT_BOUNDARIES = {
    "MOD_GSK3_1_1": (54, 61),
    "MOD_GSK3_1":   (83, 90),
    "MOD_GSK3_1_2": (132, 139),
}

def run_professor_code(
    start_seq: str,
    # --- choose which compaction metrics to optimize (set a target to include it) ---
    target_scaling_exp: float | None = 0.3,
    target_rg: float | None = None,
    target_asphericity: float | None = 0.3,

    # --- algorithm knobs (use your new defaults) ---
    buffer_size: int = 2,
    disorder_weight: float = 0.5,
    compaction_weight: float = 0.5,
    max_edit_percentage: float = 0.15,
    tolerance: float = 0.01,
    c: float = 0.003,
    penalty: float = 0.01,          # gamma in your code
    pH: float = 7.0,

    # allow client to pass custom motif boundaries
    boundaries: dict | None = None,
) -> dict:
    """
    Thin wrapper for FastAPI. Builds compaction dict, runs SA, and returns JSON-safe results.
    """

    # 1) Build compaction target dict from the parameters provided
    compaction_dict = {}
    if target_scaling_exp is not None:
        compaction_dict["scaling_exp"] = float(target_scaling_exp)
    if target_rg is not None:
        compaction_dict["scaling_rg"] = float(target_rg)
    if target_asphericity is not None:
        compaction_dict["asphericity"] = float(target_asphericity)

    if not compaction_dict:
        return {"ok": False, "error": "At least one of target_scaling_exp, target_rg, target_asphericity must be provided."}

    # 2) Prep inputs
    boundaries = boundaries or _DEFAULT_BOUNDARIES
    masked_seq, _ = mask_sequence_with_boundaries(start_seq, boundaries, buffer_size=buffer_size)

    emb, reg, dev = _get_models()
    original_disorder = aiupred_lib.predict_disorder(start_seq, emb, reg, dev)

    # 3) Run optimizer (your new SimulatedAnnealing)
    sa = SimulatedAnnealing(
        start_seq=start_seq,
        masked_seq=masked_seq,
        boundaries=boundaries,
        target_compaction=compaction_dict,
        mutation_mode="single_point",     # you weight multiple mutation types internally
        original_disorder=original_disorder,
        compaction_weight=compaction_weight,
        disorder_weight=disorder_weight,
        max_edit_percentage=max_edit_percentage,
        c=c,
        gamma=penalty,
        tolerance=tolerance,
        pH=pH,
    )

    sa.run_until_target()   # respects your defaults / stops on tolerance or max steps

    # 4) Package results
    summary = sa.get_optimization_summary()         # dict with compaction/charge/edit stats
    history_df = sa.get_history_df()                # pandas DF (only every 100th step)
    history_tail = []
    if history_df is not None and len(history_df) > 0:
        # limit to last 50 rows so payload stays small
        history_tail = history_df.tail(50).to_dict(orient="records")

    # ensure JSON-safe types
    summary = _to_py_recursive(summary)
    history_tail = _to_py_recursive(history_tail)

    return {
        "ok": True,
        "input": {
            "start_seq": start_seq,
            "targets": compaction_dict,
            "buffer_size": int(buffer_size),
            "disorder_weight": float(disorder_weight),
            "compaction_weight": float(compaction_weight),
            "max_edit_percentage": float(max_edit_percentage),
            "tolerance": float(tolerance),
            "c": float(c),
            "penalty": float(penalty),
            "pH": float(pH),
            "boundaries": boundaries,
        },
        "result": {
            "summary": summary,         # includes: converged, steps, best_sequence, best_fitness,
                                        # current_compaction, target_compaction, charge_distribution,
                                        # edit_distance, max_edits, motif_preservation, etc.
            "history_tail": history_tail
        },
    }

__all__ = ["run_professor_code"]
# ================== END FASTAPI ADAPTER =======================================
